### PR TITLE
Change scaling for task and reward widgets.

### LINKED ISSUE #71: [Bug]: Task/Reward UI elements scale inappropriately at higher resolutions
### Bug Description

Control group:
image

Realistic example (3x at 1440p)
image

Unrealistic example
image

### How to Reproduce?

_No response_

### Expected Behavior

Tasks still expand horizontally, but the task icon fills space vertically instead, avoiding inflating the task box.

here's a mockup at the realistic scale:

image

### Version

1.0.5

### Mod Loader Version

0.20.2 

### Mod Loader

Quilt

### Logs or additional context

_No response_

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

### PR DESCRIPTION
**Pull request by sisby-folk**
Closes #71

Makes the height of task and reward widgets a constant value, instead of expanding to 10% of width.
Scales non-entity icons to from 16 to 32. Fake item render helper is dusty as a result, will need cleaning on reuse.
Adjusts progress bar and submit items text to fit margins, and expands progress bar to be chunkier.
Adds a single-unit dividing line to the right of icons to avoid text clashing with certain item textures.
Fix translation keys for the newly added XP collection types because why not.

PR:

image

Release:

image

PR 1440p:

image

Release 1440p:

image

### CODE REVIEW

**Comment by CodexAdrian** [comment]
*thank you*

File: common/src/main/java/earth/terrarium/heracles/api/client/WidgetUtils.java [hunk 1]
```diff
@@ -85,14 +85,21 @@ public static void drawEntity(GuiGraphics graphics, int x, int y, int size, Enti
     }
 
     public static void drawItemIcon(GuiGraphics graphics, ItemStack icon, int x, int y, int iconSize) {
-        graphics.renderFakeItem(icon, x + 5 + (int) (iconSize / 2f) - 8, y + 5 + (int) (iconSize / 2f) - 8);
+        int scale = iconSize / 16;
+        graphics.pose().pushPose();
+        graphics.pose().translate(1, 1, 0);
+        graphics.pose().pushPose();
```
Comment (ThatGravyBoat) [inline common/src/main/java/earth/terrarium/heracles/api/client/WidgetUtils.java]: This extra pushPose seem unnecessary, also if it works correct if this is removed I would rather if the try usage is used as to show scope of push pop and to make sure that push is always popped.

Example of try push here: https://github.com/terrarium-earth/Heracles/blob/1.20.x/common/src/main/java/earth/terrarium/heracles/client/widgets/Dropdown.java#L76

**Review by ThatGravyBoat — CHANGES_REQUESTED** [review]
Also, the progress bar should be a little thinner as right now its very thick.
But overall good PR!

**Comment by sisby-folk** [comment]
I've come to love the thick progress bar alongside the rest of the non-editor Heracles GUI as being in opposition to the often annoyingly dainty UI scaling that ftb quests has, so I can't bear to cast down the knife myself 😂

It's spaced exactly as far as a third text line would be on top right now, and exactly against the margin on the bottom - if you want me to change the top, you'll have to give me an exact number to change it to, I don't have the heart lol

File: common/src/main/java/earth/terrarium/heracles/api/client/WidgetUtils.java (hunk 1 above)
Comment (sleepingdragoninn) [reply common/src/main/java/earth/terrarium/heracles/api/client/WidgetUtils.java]: done in c66fb1f along with the other use of raw pushPose in the mod. Thanks for the catch!

**Comment by ThatGravyBoat** [comment]
I think taking off 2 pixels so that the text and progress bar are the same height.
You can then move the text down 1 pixel each and the bar up 1 pixel then they'll be spaced the same as before and all proportions will be perfect.

Heres an example with those numbers I did in paint 
image

**Comment by sisby-folk** [comment]
Here's that!

image

**Comment by sisby-folk** [comment]
ah hold on, missed the number.

**Comment by sisby-folk** [comment]
There we go.
image

**Review by ThatGravyBoat — APPROVED** [review]
Looks great!
